services:
  - type: web
    name: vindio-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Chatbot.py --serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    scaling:
      minInstances: 1
